name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  build-and-deploy:    
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-project-key: marcelocasteloio_MCIO.OutputEnvelop
        sonar-organization: marcelocasteloio
        sonar-host-url: https://sonarcloud.io
        sonar-cs-opencover-reportsPaths: '**/coverage.opencover.xml'
        sonar-coverage-exclusions: 'tst/**,benchs/**,samples/**'
        sonar-exclusions: 'tst/**,benchs/**,samples/**'

    - name: Build And Test
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="Coverage/" ./tst/UnitTests/MCIO.OutputEnvelop.UnitTests.csproj

    - name: Complete SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}

    - name: SonarQube Quality Gate Check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: https://sonarcloud.io
        check-name: SonarQube Quality Gate Check

    - name: Install Stryker
      shell: pwsh
      run: |
        New-Item -Path ./.stryker/stryker -ItemType Directory
        dotnet tool update dotnet-stryker --tool-path ./.stryker/stryker

    - name: Restore Dependencies
      run: dotnet restore
    
    - name: Mutant Tests
      shell: pwsh
      run: |
        cd ./tst/UnitTests
        ../../.stryker/stryker/dotnet-stryker --reporter "cleartext"

