name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'     
        required: true
        default: '0.0.0'

jobs:
  
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit

  pack-and-publish:
    name: Pack and Publish
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    
    - name: Pack
      run: dotnet pack -c Release src/OutputEnvelop/MCIO.OutputEnvelop.csproj /p:Version='${{ github.event.inputs.version }}' --include-symbols --include-source

    - name: Publish
      run: dotnet nuget push **/*${{ github.event.inputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
